### ISSUE TITLE
Motion npy

### ISSUE THREAD

**Issue by mp3pintyo** [jeolpyeoni/StyleCineGAN#3]
How can I create a motion npy file for my own image?

**Comment by jeolpyeoni** [comment]
Thank you for showing interest in our work!
We provide StyleGAN2 and encoder checkpoints so that our proposed MSDFW method can be used for comparison with following researches.

For motion generation, we followed [Text2Cinemagraph](https://github.com/text2cinemagraph/text2cinemagraph) paper,
thus you can refer to the codes to produce your own motion file.

Or, you can train [pix2pixHD](https://github.com/NVIDIA/pix2pixHD) on [Sky-Timelapse](https://github.com/zhangzjn/DTVNet) and [Eulerian](https://eulerian.cs.washington.edu/dataset/) dataset to train your own motion generation network.

**Comment by penghaohsu** [comment]
Hi, I'm curious about how you generate motion.npy from [Text2Cinemagraph](https://github.com/text2cinemagraph/text2cinemagraph) paper. I can only generate motions with a fixed width and height (512, 512) from it. To use an input image with different width and height, how can I process it and apply to your work? 
Thanks for your great work!

**Comment by jeolpyeoni** [comment]
Hello,

it is ok to utilize the motion field at the resolution of 512 x 512, where resizing of the optical flow is already implemented in the code (we resize it for every resolutions that we operate).

The scheme is quite simple, we perform bilinear interpolation, and multiply by a scaling factor (= res / 512)
