### ISSUE TITLE
May I ask what solution is used to generate optical flow diagram using sky_timelapse?

### ISSUE THREAD

**Issue by tscvividly** [jeolpyeoni/StyleCineGAN#4]
I use pyflow or raft to take several adjacent frames to generate an optical flow map, and then input the optical flow map and pictures into cinegan. Some data generation effects are relatively poor.

So what solution is used to generate the optical flow map that is better used as the label of pix2pixHD?

**Comment by jeolpyeoni** [comment]
Hello, thanks for showing your interest in our work!

In our paper, we utilized RAFT model, computing optical flow of adjacent frames within 2-seconds time window.
Because the model prediction is not always perfect, and some videos may contain too complex motion, the result can sometimes be unsatisfactory.

To minimize the optical flow prediction errors, we performed additional processing on optical flows.
1) We performed z-score filtering on optical flow, so erroneous values with significant magnitudes can be filtered out.
2) We provide segmentation mask of moving regions (sky, fluids) to isolate the motions.

If you have any further questions, please feel free to ask!
